spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    defer-datasource-initialization: false
    open-in-view: false
server:
  port: 8030
secret: secretKeyExampleForJsonWebTokenAndSecurityServiceAndForUserJwtServiceForCreateJsonWebToken
