spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee
          uri: http://localhost:8010
          predicates:
            - Path=/employees/**
        - id: company
          uri: http://localhost:8020
          predicates:
            - Path=/companies/**
        - id: authentication
          uri: http://localhost:8030
          predicates:
            - Path=/auth/**
server:
  port: 8090


