spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
eureka:
  client:
    register-with-eureka: false
server:
  port: 8090


